import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header'
import Section from '../components/Section'
import Founding from '../components/Staking/Founding'

const vault: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Metaverse Staking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header textAuxButton="Vault" href='/vault' />
        <Section title='VAULT' content={<Founding image='/images/founding-img-test.png' />} description="" />
      </main>
    </div>
  )
}

export default vault